/*
 * CD NextGen API Reference
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 3.0
 * Contact: contact@harness.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BudgetCostData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T23:54:49.094+05:30[Asia/Kolkata]")
public class BudgetCostData {
  @SerializedName("time")
  private Long time = null;

  @SerializedName("endTime")
  private Long endTime = null;

  @SerializedName("actualCost")
  private Double actualCost = null;

  @SerializedName("budgeted")
  private Double budgeted = null;

  @SerializedName("budgetVariance")
  private Double budgetVariance = null;

  @SerializedName("budgetVariancePercentage")
  private Double budgetVariancePercentage = null;

  public BudgetCostData time(Long time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @Schema(description = "")
  public Long getTime() {
    return time;
  }

  public void setTime(Long time) {
    this.time = time;
  }

  public BudgetCostData endTime(Long endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @Schema(description = "")
  public Long getEndTime() {
    return endTime;
  }

  public void setEndTime(Long endTime) {
    this.endTime = endTime;
  }

  public BudgetCostData actualCost(Double actualCost) {
    this.actualCost = actualCost;
    return this;
  }

   /**
   * Get actualCost
   * @return actualCost
  **/
  @Schema(description = "")
  public Double getActualCost() {
    return actualCost;
  }

  public void setActualCost(Double actualCost) {
    this.actualCost = actualCost;
  }

  public BudgetCostData budgeted(Double budgeted) {
    this.budgeted = budgeted;
    return this;
  }

   /**
   * Get budgeted
   * @return budgeted
  **/
  @Schema(description = "")
  public Double getBudgeted() {
    return budgeted;
  }

  public void setBudgeted(Double budgeted) {
    this.budgeted = budgeted;
  }

  public BudgetCostData budgetVariance(Double budgetVariance) {
    this.budgetVariance = budgetVariance;
    return this;
  }

   /**
   * Get budgetVariance
   * @return budgetVariance
  **/
  @Schema(description = "")
  public Double getBudgetVariance() {
    return budgetVariance;
  }

  public void setBudgetVariance(Double budgetVariance) {
    this.budgetVariance = budgetVariance;
  }

  public BudgetCostData budgetVariancePercentage(Double budgetVariancePercentage) {
    this.budgetVariancePercentage = budgetVariancePercentage;
    return this;
  }

   /**
   * Get budgetVariancePercentage
   * @return budgetVariancePercentage
  **/
  @Schema(description = "")
  public Double getBudgetVariancePercentage() {
    return budgetVariancePercentage;
  }

  public void setBudgetVariancePercentage(Double budgetVariancePercentage) {
    this.budgetVariancePercentage = budgetVariancePercentage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BudgetCostData budgetCostData = (BudgetCostData) o;
    return Objects.equals(this.time, budgetCostData.time) &&
        Objects.equals(this.endTime, budgetCostData.endTime) &&
        Objects.equals(this.actualCost, budgetCostData.actualCost) &&
        Objects.equals(this.budgeted, budgetCostData.budgeted) &&
        Objects.equals(this.budgetVariance, budgetCostData.budgetVariance) &&
        Objects.equals(this.budgetVariancePercentage, budgetCostData.budgetVariancePercentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, endTime, actualCost, budgeted, budgetVariance, budgetVariancePercentage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BudgetCostData {\n");
    
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    actualCost: ").append(toIndentedString(actualCost)).append("\n");
    sb.append("    budgeted: ").append(toIndentedString(budgeted)).append("\n");
    sb.append("    budgetVariance: ").append(toIndentedString(budgetVariance)).append("\n");
    sb.append("    budgetVariancePercentage: ").append(toIndentedString(budgetVariancePercentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
