/*
 * CD NextGen API Reference
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 3.0
 * Contact: contact@harness.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.OnFailureConfig;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FailureStrategyConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T23:54:49.094+05:30[Asia/Kolkata]")
public class FailureStrategyConfig {
  @SerializedName("onFailure")
  private OnFailureConfig onFailure = null;

  public FailureStrategyConfig onFailure(OnFailureConfig onFailure) {
    this.onFailure = onFailure;
    return this;
  }

   /**
   * Get onFailure
   * @return onFailure
  **/
  @Schema(required = true, description = "")
  public OnFailureConfig getOnFailure() {
    return onFailure;
  }

  public void setOnFailure(OnFailureConfig onFailure) {
    this.onFailure = onFailure;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FailureStrategyConfig failureStrategyConfig = (FailureStrategyConfig) o;
    return Objects.equals(this.onFailure, failureStrategyConfig.onFailure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(onFailure);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FailureStrategyConfig {\n");
    
    sb.append("    onFailure: ").append(toIndentedString(onFailure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
