/*
 * CD NextGen API Reference
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 3.0
 * Contact: contact@harness.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Descriptor;
import io.swagger.client.model.FieldOptions;
import io.swagger.client.model.ParserFieldOptions;
import io.swagger.client.model.UninterpretedOption;
import io.swagger.client.model.UninterpretedOptionOrBuilder;
import io.swagger.client.model.UnknownFieldSet;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * FieldOptions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T23:54:49.094+05:30[Asia/Kolkata]")
public class FieldOptions {
  @SerializedName("unknownFields")
  private UnknownFieldSet unknownFields = null;

  @SerializedName("initialized")
  private Boolean initialized = null;

  @SerializedName("packed")
  private Boolean packed = null;

  /**
   * Gets or Sets jstype
   */
  @JsonAdapter(JstypeEnum.Adapter.class)
  public enum JstypeEnum {
    NORMAL("JS_NORMAL"),
    STRING("JS_STRING"),
    NUMBER("JS_NUMBER");

    private String value;

    JstypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static JstypeEnum fromValue(String input) {
      for (JstypeEnum b : JstypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<JstypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final JstypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public JstypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return JstypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("jstype")
  private JstypeEnum jstype = null;

  @SerializedName("weak")
  private Boolean weak = null;

  @SerializedName("lazy")
  private Boolean lazy = null;

  @SerializedName("deprecated")
  private Boolean deprecated = null;

  @SerializedName("uninterpretedOptionList")
  private List<UninterpretedOption> uninterpretedOptionList = null;

  @SerializedName("uninterpretedOptionCount")
  private Integer uninterpretedOptionCount = null;

  @SerializedName("uninterpretedOptionOrBuilderList")
  private List<UninterpretedOptionOrBuilder> uninterpretedOptionOrBuilderList = null;

  @SerializedName("serializedSize")
  private Integer serializedSize = null;

  @SerializedName("parserForType")
  private ParserFieldOptions parserForType = null;

  @SerializedName("defaultInstanceForType")
  private FieldOptions defaultInstanceForType = null;

  /**
   * Gets or Sets ctype
   */
  @JsonAdapter(CtypeEnum.Adapter.class)
  public enum CtypeEnum {
    STRING("STRING"),
    CORD("CORD"),
    STRING_PIECE("STRING_PIECE");

    private String value;

    CtypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static CtypeEnum fromValue(String input) {
      for (CtypeEnum b : CtypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<CtypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CtypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public CtypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return CtypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("ctype")
  private CtypeEnum ctype = null;

  @SerializedName("allFields")
  private Map<String, Object> allFields = null;

  @SerializedName("initializationErrorString")
  private String initializationErrorString = null;

  @SerializedName("descriptorForType")
  private Descriptor descriptorForType = null;

  @SerializedName("allFieldsRaw")
  private Map<String, Object> allFieldsRaw = null;

  @SerializedName("memoizedSerializedSize")
  private Integer memoizedSerializedSize = null;

  public FieldOptions unknownFields(UnknownFieldSet unknownFields) {
    this.unknownFields = unknownFields;
    return this;
  }

   /**
   * Get unknownFields
   * @return unknownFields
  **/
  @Schema(description = "")
  public UnknownFieldSet getUnknownFields() {
    return unknownFields;
  }

  public void setUnknownFields(UnknownFieldSet unknownFields) {
    this.unknownFields = unknownFields;
  }

  public FieldOptions initialized(Boolean initialized) {
    this.initialized = initialized;
    return this;
  }

   /**
   * Get initialized
   * @return initialized
  **/
  @Schema(description = "")
  public Boolean isInitialized() {
    return initialized;
  }

  public void setInitialized(Boolean initialized) {
    this.initialized = initialized;
  }

  public FieldOptions packed(Boolean packed) {
    this.packed = packed;
    return this;
  }

   /**
   * Get packed
   * @return packed
  **/
  @Schema(description = "")
  public Boolean isPacked() {
    return packed;
  }

  public void setPacked(Boolean packed) {
    this.packed = packed;
  }

  public FieldOptions jstype(JstypeEnum jstype) {
    this.jstype = jstype;
    return this;
  }

   /**
   * Get jstype
   * @return jstype
  **/
  @Schema(description = "")
  public JstypeEnum getJstype() {
    return jstype;
  }

  public void setJstype(JstypeEnum jstype) {
    this.jstype = jstype;
  }

  public FieldOptions weak(Boolean weak) {
    this.weak = weak;
    return this;
  }

   /**
   * Get weak
   * @return weak
  **/
  @Schema(description = "")
  public Boolean isWeak() {
    return weak;
  }

  public void setWeak(Boolean weak) {
    this.weak = weak;
  }

  public FieldOptions lazy(Boolean lazy) {
    this.lazy = lazy;
    return this;
  }

   /**
   * Get lazy
   * @return lazy
  **/
  @Schema(description = "")
  public Boolean isLazy() {
    return lazy;
  }

  public void setLazy(Boolean lazy) {
    this.lazy = lazy;
  }

  public FieldOptions deprecated(Boolean deprecated) {
    this.deprecated = deprecated;
    return this;
  }

   /**
   * Get deprecated
   * @return deprecated
  **/
  @Schema(description = "")
  public Boolean isDeprecated() {
    return deprecated;
  }

  public void setDeprecated(Boolean deprecated) {
    this.deprecated = deprecated;
  }

  public FieldOptions uninterpretedOptionList(List<UninterpretedOption> uninterpretedOptionList) {
    this.uninterpretedOptionList = uninterpretedOptionList;
    return this;
  }

  public FieldOptions addUninterpretedOptionListItem(UninterpretedOption uninterpretedOptionListItem) {
    if (this.uninterpretedOptionList == null) {
      this.uninterpretedOptionList = new ArrayList<UninterpretedOption>();
    }
    this.uninterpretedOptionList.add(uninterpretedOptionListItem);
    return this;
  }

   /**
   * Get uninterpretedOptionList
   * @return uninterpretedOptionList
  **/
  @Schema(description = "")
  public List<UninterpretedOption> getUninterpretedOptionList() {
    return uninterpretedOptionList;
  }

  public void setUninterpretedOptionList(List<UninterpretedOption> uninterpretedOptionList) {
    this.uninterpretedOptionList = uninterpretedOptionList;
  }

  public FieldOptions uninterpretedOptionCount(Integer uninterpretedOptionCount) {
    this.uninterpretedOptionCount = uninterpretedOptionCount;
    return this;
  }

   /**
   * Get uninterpretedOptionCount
   * @return uninterpretedOptionCount
  **/
  @Schema(description = "")
  public Integer getUninterpretedOptionCount() {
    return uninterpretedOptionCount;
  }

  public void setUninterpretedOptionCount(Integer uninterpretedOptionCount) {
    this.uninterpretedOptionCount = uninterpretedOptionCount;
  }

  public FieldOptions uninterpretedOptionOrBuilderList(List<UninterpretedOptionOrBuilder> uninterpretedOptionOrBuilderList) {
    this.uninterpretedOptionOrBuilderList = uninterpretedOptionOrBuilderList;
    return this;
  }

  public FieldOptions addUninterpretedOptionOrBuilderListItem(UninterpretedOptionOrBuilder uninterpretedOptionOrBuilderListItem) {
    if (this.uninterpretedOptionOrBuilderList == null) {
      this.uninterpretedOptionOrBuilderList = new ArrayList<UninterpretedOptionOrBuilder>();
    }
    this.uninterpretedOptionOrBuilderList.add(uninterpretedOptionOrBuilderListItem);
    return this;
  }

   /**
   * Get uninterpretedOptionOrBuilderList
   * @return uninterpretedOptionOrBuilderList
  **/
  @Schema(description = "")
  public List<UninterpretedOptionOrBuilder> getUninterpretedOptionOrBuilderList() {
    return uninterpretedOptionOrBuilderList;
  }

  public void setUninterpretedOptionOrBuilderList(List<UninterpretedOptionOrBuilder> uninterpretedOptionOrBuilderList) {
    this.uninterpretedOptionOrBuilderList = uninterpretedOptionOrBuilderList;
  }

  public FieldOptions serializedSize(Integer serializedSize) {
    this.serializedSize = serializedSize;
    return this;
  }

   /**
   * Get serializedSize
   * @return serializedSize
  **/
  @Schema(description = "")
  public Integer getSerializedSize() {
    return serializedSize;
  }

  public void setSerializedSize(Integer serializedSize) {
    this.serializedSize = serializedSize;
  }

  public FieldOptions parserForType(ParserFieldOptions parserForType) {
    this.parserForType = parserForType;
    return this;
  }

   /**
   * Get parserForType
   * @return parserForType
  **/
  @Schema(description = "")
  public ParserFieldOptions getParserForType() {
    return parserForType;
  }

  public void setParserForType(ParserFieldOptions parserForType) {
    this.parserForType = parserForType;
  }

  public FieldOptions defaultInstanceForType(FieldOptions defaultInstanceForType) {
    this.defaultInstanceForType = defaultInstanceForType;
    return this;
  }

   /**
   * Get defaultInstanceForType
   * @return defaultInstanceForType
  **/
  @Schema(description = "")
  public FieldOptions getDefaultInstanceForType() {
    return defaultInstanceForType;
  }

  public void setDefaultInstanceForType(FieldOptions defaultInstanceForType) {
    this.defaultInstanceForType = defaultInstanceForType;
  }

  public FieldOptions ctype(CtypeEnum ctype) {
    this.ctype = ctype;
    return this;
  }

   /**
   * Get ctype
   * @return ctype
  **/
  @Schema(description = "")
  public CtypeEnum getCtype() {
    return ctype;
  }

  public void setCtype(CtypeEnum ctype) {
    this.ctype = ctype;
  }

  public FieldOptions allFields(Map<String, Object> allFields) {
    this.allFields = allFields;
    return this;
  }

  public FieldOptions putAllFieldsItem(String key, Object allFieldsItem) {
    if (this.allFields == null) {
      this.allFields = new HashMap<String, Object>();
    }
    this.allFields.put(key, allFieldsItem);
    return this;
  }

   /**
   * Get allFields
   * @return allFields
  **/
  @Schema(description = "")
  public Map<String, Object> getAllFields() {
    return allFields;
  }

  public void setAllFields(Map<String, Object> allFields) {
    this.allFields = allFields;
  }

  public FieldOptions initializationErrorString(String initializationErrorString) {
    this.initializationErrorString = initializationErrorString;
    return this;
  }

   /**
   * Get initializationErrorString
   * @return initializationErrorString
  **/
  @Schema(description = "")
  public String getInitializationErrorString() {
    return initializationErrorString;
  }

  public void setInitializationErrorString(String initializationErrorString) {
    this.initializationErrorString = initializationErrorString;
  }

  public FieldOptions descriptorForType(Descriptor descriptorForType) {
    this.descriptorForType = descriptorForType;
    return this;
  }

   /**
   * Get descriptorForType
   * @return descriptorForType
  **/
  @Schema(description = "")
  public Descriptor getDescriptorForType() {
    return descriptorForType;
  }

  public void setDescriptorForType(Descriptor descriptorForType) {
    this.descriptorForType = descriptorForType;
  }

  public FieldOptions allFieldsRaw(Map<String, Object> allFieldsRaw) {
    this.allFieldsRaw = allFieldsRaw;
    return this;
  }

  public FieldOptions putAllFieldsRawItem(String key, Object allFieldsRawItem) {
    if (this.allFieldsRaw == null) {
      this.allFieldsRaw = new HashMap<String, Object>();
    }
    this.allFieldsRaw.put(key, allFieldsRawItem);
    return this;
  }

   /**
   * Get allFieldsRaw
   * @return allFieldsRaw
  **/
  @Schema(description = "")
  public Map<String, Object> getAllFieldsRaw() {
    return allFieldsRaw;
  }

  public void setAllFieldsRaw(Map<String, Object> allFieldsRaw) {
    this.allFieldsRaw = allFieldsRaw;
  }

  public FieldOptions memoizedSerializedSize(Integer memoizedSerializedSize) {
    this.memoizedSerializedSize = memoizedSerializedSize;
    return this;
  }

   /**
   * Get memoizedSerializedSize
   * @return memoizedSerializedSize
  **/
  @Schema(description = "")
  public Integer getMemoizedSerializedSize() {
    return memoizedSerializedSize;
  }

  public void setMemoizedSerializedSize(Integer memoizedSerializedSize) {
    this.memoizedSerializedSize = memoizedSerializedSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldOptions fieldOptions = (FieldOptions) o;
    return Objects.equals(this.unknownFields, fieldOptions.unknownFields) &&
        Objects.equals(this.initialized, fieldOptions.initialized) &&
        Objects.equals(this.packed, fieldOptions.packed) &&
        Objects.equals(this.jstype, fieldOptions.jstype) &&
        Objects.equals(this.weak, fieldOptions.weak) &&
        Objects.equals(this.lazy, fieldOptions.lazy) &&
        Objects.equals(this.deprecated, fieldOptions.deprecated) &&
        Objects.equals(this.uninterpretedOptionList, fieldOptions.uninterpretedOptionList) &&
        Objects.equals(this.uninterpretedOptionCount, fieldOptions.uninterpretedOptionCount) &&
        Objects.equals(this.uninterpretedOptionOrBuilderList, fieldOptions.uninterpretedOptionOrBuilderList) &&
        Objects.equals(this.serializedSize, fieldOptions.serializedSize) &&
        Objects.equals(this.parserForType, fieldOptions.parserForType) &&
        Objects.equals(this.defaultInstanceForType, fieldOptions.defaultInstanceForType) &&
        Objects.equals(this.ctype, fieldOptions.ctype) &&
        Objects.equals(this.allFields, fieldOptions.allFields) &&
        Objects.equals(this.initializationErrorString, fieldOptions.initializationErrorString) &&
        Objects.equals(this.descriptorForType, fieldOptions.descriptorForType) &&
        Objects.equals(this.allFieldsRaw, fieldOptions.allFieldsRaw) &&
        Objects.equals(this.memoizedSerializedSize, fieldOptions.memoizedSerializedSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unknownFields, initialized, packed, jstype, weak, lazy, deprecated, uninterpretedOptionList, uninterpretedOptionCount, uninterpretedOptionOrBuilderList, serializedSize, parserForType, defaultInstanceForType, ctype, allFields, initializationErrorString, descriptorForType, allFieldsRaw, memoizedSerializedSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldOptions {\n");
    
    sb.append("    unknownFields: ").append(toIndentedString(unknownFields)).append("\n");
    sb.append("    initialized: ").append(toIndentedString(initialized)).append("\n");
    sb.append("    packed: ").append(toIndentedString(packed)).append("\n");
    sb.append("    jstype: ").append(toIndentedString(jstype)).append("\n");
    sb.append("    weak: ").append(toIndentedString(weak)).append("\n");
    sb.append("    lazy: ").append(toIndentedString(lazy)).append("\n");
    sb.append("    deprecated: ").append(toIndentedString(deprecated)).append("\n");
    sb.append("    uninterpretedOptionList: ").append(toIndentedString(uninterpretedOptionList)).append("\n");
    sb.append("    uninterpretedOptionCount: ").append(toIndentedString(uninterpretedOptionCount)).append("\n");
    sb.append("    uninterpretedOptionOrBuilderList: ").append(toIndentedString(uninterpretedOptionOrBuilderList)).append("\n");
    sb.append("    serializedSize: ").append(toIndentedString(serializedSize)).append("\n");
    sb.append("    parserForType: ").append(toIndentedString(parserForType)).append("\n");
    sb.append("    defaultInstanceForType: ").append(toIndentedString(defaultInstanceForType)).append("\n");
    sb.append("    ctype: ").append(toIndentedString(ctype)).append("\n");
    sb.append("    allFields: ").append(toIndentedString(allFields)).append("\n");
    sb.append("    initializationErrorString: ").append(toIndentedString(initializationErrorString)).append("\n");
    sb.append("    descriptorForType: ").append(toIndentedString(descriptorForType)).append("\n");
    sb.append("    allFieldsRaw: ").append(toIndentedString(allFieldsRaw)).append("\n");
    sb.append("    memoizedSerializedSize: ").append(toIndentedString(memoizedSerializedSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
