/*
 * CD NextGen API Reference
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 3.0
 * Contact: contact@harness.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.GitBranch;
import io.swagger.client.model.PageResponseGitBranch;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * This contains details of the default and other branch
 */
@Schema(description = "This contains details of the default and other branch")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T23:54:49.094+05:30[Asia/Kolkata]")
public class GitBranchList {
  @SerializedName("defaultBranch")
  private GitBranch defaultBranch = null;

  @SerializedName("branches")
  private PageResponseGitBranch branches = null;

  public GitBranchList defaultBranch(GitBranch defaultBranch) {
    this.defaultBranch = defaultBranch;
    return this;
  }

   /**
   * Get defaultBranch
   * @return defaultBranch
  **/
  @Schema(description = "")
  public GitBranch getDefaultBranch() {
    return defaultBranch;
  }

  public void setDefaultBranch(GitBranch defaultBranch) {
    this.defaultBranch = defaultBranch;
  }

  public GitBranchList branches(PageResponseGitBranch branches) {
    this.branches = branches;
    return this;
  }

   /**
   * Get branches
   * @return branches
  **/
  @Schema(description = "")
  public PageResponseGitBranch getBranches() {
    return branches;
  }

  public void setBranches(PageResponseGitBranch branches) {
    this.branches = branches;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GitBranchList gitBranchList = (GitBranchList) o;
    return Objects.equals(this.defaultBranch, gitBranchList.defaultBranch) &&
        Objects.equals(this.branches, gitBranchList.branches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultBranch, branches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GitBranchList {\n");
    
    sb.append("    defaultBranch: ").append(toIndentedString(defaultBranch)).append("\n");
    sb.append("    branches: ").append(toIndentedString(branches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
