/*
 * CD NextGen API Reference
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 3.0
 * Contact: contact@harness.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ByteString;
import io.swagger.client.model.Descriptor;
import io.swagger.client.model.ParserRerunInfo;
import io.swagger.client.model.RerunInfo;
import io.swagger.client.model.UnknownFieldSet;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * RerunInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T23:54:49.094+05:30[Asia/Kolkata]")
public class RerunInfo {
  @SerializedName("unknownFields")
  private UnknownFieldSet unknownFields = null;

  @SerializedName("initialized")
  private Boolean initialized = null;

  @SerializedName("rootExecutionId")
  private String rootExecutionId = null;

  @SerializedName("rootTriggerTypeValue")
  private Integer rootTriggerTypeValue = null;

  @SerializedName("prevExecutionId")
  private String prevExecutionId = null;

  @SerializedName("prevExecutionIdBytes")
  private ByteString prevExecutionIdBytes = null;

  @SerializedName("prevTriggerTypeValue")
  private Integer prevTriggerTypeValue = null;

  /**
   * Gets or Sets prevTriggerType
   */
  @JsonAdapter(PrevTriggerTypeEnum.Adapter.class)
  public enum PrevTriggerTypeEnum {
    NOOP("NOOP"),
    MANUAL("MANUAL"),
    WEBHOOK("WEBHOOK"),
    WEBHOOK_CUSTOM("WEBHOOK_CUSTOM"),
    SCHEDULER_CRON("SCHEDULER_CRON"),
    UNRECOGNIZED("UNRECOGNIZED");

    private String value;

    PrevTriggerTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static PrevTriggerTypeEnum fromValue(String input) {
      for (PrevTriggerTypeEnum b : PrevTriggerTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<PrevTriggerTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PrevTriggerTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public PrevTriggerTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return PrevTriggerTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("prevTriggerType")
  private PrevTriggerTypeEnum prevTriggerType = null;

  @SerializedName("rootExecutionIdBytes")
  private ByteString rootExecutionIdBytes = null;

  @SerializedName("serializedSize")
  private Integer serializedSize = null;

  @SerializedName("parserForType")
  private ParserRerunInfo parserForType = null;

  @SerializedName("defaultInstanceForType")
  private RerunInfo defaultInstanceForType = null;

  /**
   * Gets or Sets rootTriggerType
   */
  @JsonAdapter(RootTriggerTypeEnum.Adapter.class)
  public enum RootTriggerTypeEnum {
    NOOP("NOOP"),
    MANUAL("MANUAL"),
    WEBHOOK("WEBHOOK"),
    WEBHOOK_CUSTOM("WEBHOOK_CUSTOM"),
    SCHEDULER_CRON("SCHEDULER_CRON"),
    UNRECOGNIZED("UNRECOGNIZED");

    private String value;

    RootTriggerTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static RootTriggerTypeEnum fromValue(String input) {
      for (RootTriggerTypeEnum b : RootTriggerTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<RootTriggerTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RootTriggerTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public RootTriggerTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return RootTriggerTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("rootTriggerType")
  private RootTriggerTypeEnum rootTriggerType = null;

  @SerializedName("allFields")
  private Map<String, Object> allFields = null;

  @SerializedName("initializationErrorString")
  private String initializationErrorString = null;

  @SerializedName("descriptorForType")
  private Descriptor descriptorForType = null;

  @SerializedName("memoizedSerializedSize")
  private Integer memoizedSerializedSize = null;

  public RerunInfo unknownFields(UnknownFieldSet unknownFields) {
    this.unknownFields = unknownFields;
    return this;
  }

   /**
   * Get unknownFields
   * @return unknownFields
  **/
  @Schema(description = "")
  public UnknownFieldSet getUnknownFields() {
    return unknownFields;
  }

  public void setUnknownFields(UnknownFieldSet unknownFields) {
    this.unknownFields = unknownFields;
  }

  public RerunInfo initialized(Boolean initialized) {
    this.initialized = initialized;
    return this;
  }

   /**
   * Get initialized
   * @return initialized
  **/
  @Schema(description = "")
  public Boolean isInitialized() {
    return initialized;
  }

  public void setInitialized(Boolean initialized) {
    this.initialized = initialized;
  }

  public RerunInfo rootExecutionId(String rootExecutionId) {
    this.rootExecutionId = rootExecutionId;
    return this;
  }

   /**
   * Get rootExecutionId
   * @return rootExecutionId
  **/
  @Schema(description = "")
  public String getRootExecutionId() {
    return rootExecutionId;
  }

  public void setRootExecutionId(String rootExecutionId) {
    this.rootExecutionId = rootExecutionId;
  }

  public RerunInfo rootTriggerTypeValue(Integer rootTriggerTypeValue) {
    this.rootTriggerTypeValue = rootTriggerTypeValue;
    return this;
  }

   /**
   * Get rootTriggerTypeValue
   * @return rootTriggerTypeValue
  **/
  @Schema(description = "")
  public Integer getRootTriggerTypeValue() {
    return rootTriggerTypeValue;
  }

  public void setRootTriggerTypeValue(Integer rootTriggerTypeValue) {
    this.rootTriggerTypeValue = rootTriggerTypeValue;
  }

  public RerunInfo prevExecutionId(String prevExecutionId) {
    this.prevExecutionId = prevExecutionId;
    return this;
  }

   /**
   * Get prevExecutionId
   * @return prevExecutionId
  **/
  @Schema(description = "")
  public String getPrevExecutionId() {
    return prevExecutionId;
  }

  public void setPrevExecutionId(String prevExecutionId) {
    this.prevExecutionId = prevExecutionId;
  }

  public RerunInfo prevExecutionIdBytes(ByteString prevExecutionIdBytes) {
    this.prevExecutionIdBytes = prevExecutionIdBytes;
    return this;
  }

   /**
   * Get prevExecutionIdBytes
   * @return prevExecutionIdBytes
  **/
  @Schema(description = "")
  public ByteString getPrevExecutionIdBytes() {
    return prevExecutionIdBytes;
  }

  public void setPrevExecutionIdBytes(ByteString prevExecutionIdBytes) {
    this.prevExecutionIdBytes = prevExecutionIdBytes;
  }

  public RerunInfo prevTriggerTypeValue(Integer prevTriggerTypeValue) {
    this.prevTriggerTypeValue = prevTriggerTypeValue;
    return this;
  }

   /**
   * Get prevTriggerTypeValue
   * @return prevTriggerTypeValue
  **/
  @Schema(description = "")
  public Integer getPrevTriggerTypeValue() {
    return prevTriggerTypeValue;
  }

  public void setPrevTriggerTypeValue(Integer prevTriggerTypeValue) {
    this.prevTriggerTypeValue = prevTriggerTypeValue;
  }

  public RerunInfo prevTriggerType(PrevTriggerTypeEnum prevTriggerType) {
    this.prevTriggerType = prevTriggerType;
    return this;
  }

   /**
   * Get prevTriggerType
   * @return prevTriggerType
  **/
  @Schema(description = "")
  public PrevTriggerTypeEnum getPrevTriggerType() {
    return prevTriggerType;
  }

  public void setPrevTriggerType(PrevTriggerTypeEnum prevTriggerType) {
    this.prevTriggerType = prevTriggerType;
  }

  public RerunInfo rootExecutionIdBytes(ByteString rootExecutionIdBytes) {
    this.rootExecutionIdBytes = rootExecutionIdBytes;
    return this;
  }

   /**
   * Get rootExecutionIdBytes
   * @return rootExecutionIdBytes
  **/
  @Schema(description = "")
  public ByteString getRootExecutionIdBytes() {
    return rootExecutionIdBytes;
  }

  public void setRootExecutionIdBytes(ByteString rootExecutionIdBytes) {
    this.rootExecutionIdBytes = rootExecutionIdBytes;
  }

  public RerunInfo serializedSize(Integer serializedSize) {
    this.serializedSize = serializedSize;
    return this;
  }

   /**
   * Get serializedSize
   * @return serializedSize
  **/
  @Schema(description = "")
  public Integer getSerializedSize() {
    return serializedSize;
  }

  public void setSerializedSize(Integer serializedSize) {
    this.serializedSize = serializedSize;
  }

  public RerunInfo parserForType(ParserRerunInfo parserForType) {
    this.parserForType = parserForType;
    return this;
  }

   /**
   * Get parserForType
   * @return parserForType
  **/
  @Schema(description = "")
  public ParserRerunInfo getParserForType() {
    return parserForType;
  }

  public void setParserForType(ParserRerunInfo parserForType) {
    this.parserForType = parserForType;
  }

  public RerunInfo defaultInstanceForType(RerunInfo defaultInstanceForType) {
    this.defaultInstanceForType = defaultInstanceForType;
    return this;
  }

   /**
   * Get defaultInstanceForType
   * @return defaultInstanceForType
  **/
  @Schema(description = "")
  public RerunInfo getDefaultInstanceForType() {
    return defaultInstanceForType;
  }

  public void setDefaultInstanceForType(RerunInfo defaultInstanceForType) {
    this.defaultInstanceForType = defaultInstanceForType;
  }

  public RerunInfo rootTriggerType(RootTriggerTypeEnum rootTriggerType) {
    this.rootTriggerType = rootTriggerType;
    return this;
  }

   /**
   * Get rootTriggerType
   * @return rootTriggerType
  **/
  @Schema(description = "")
  public RootTriggerTypeEnum getRootTriggerType() {
    return rootTriggerType;
  }

  public void setRootTriggerType(RootTriggerTypeEnum rootTriggerType) {
    this.rootTriggerType = rootTriggerType;
  }

  public RerunInfo allFields(Map<String, Object> allFields) {
    this.allFields = allFields;
    return this;
  }

  public RerunInfo putAllFieldsItem(String key, Object allFieldsItem) {
    if (this.allFields == null) {
      this.allFields = new HashMap<String, Object>();
    }
    this.allFields.put(key, allFieldsItem);
    return this;
  }

   /**
   * Get allFields
   * @return allFields
  **/
  @Schema(description = "")
  public Map<String, Object> getAllFields() {
    return allFields;
  }

  public void setAllFields(Map<String, Object> allFields) {
    this.allFields = allFields;
  }

  public RerunInfo initializationErrorString(String initializationErrorString) {
    this.initializationErrorString = initializationErrorString;
    return this;
  }

   /**
   * Get initializationErrorString
   * @return initializationErrorString
  **/
  @Schema(description = "")
  public String getInitializationErrorString() {
    return initializationErrorString;
  }

  public void setInitializationErrorString(String initializationErrorString) {
    this.initializationErrorString = initializationErrorString;
  }

  public RerunInfo descriptorForType(Descriptor descriptorForType) {
    this.descriptorForType = descriptorForType;
    return this;
  }

   /**
   * Get descriptorForType
   * @return descriptorForType
  **/
  @Schema(description = "")
  public Descriptor getDescriptorForType() {
    return descriptorForType;
  }

  public void setDescriptorForType(Descriptor descriptorForType) {
    this.descriptorForType = descriptorForType;
  }

  public RerunInfo memoizedSerializedSize(Integer memoizedSerializedSize) {
    this.memoizedSerializedSize = memoizedSerializedSize;
    return this;
  }

   /**
   * Get memoizedSerializedSize
   * @return memoizedSerializedSize
  **/
  @Schema(description = "")
  public Integer getMemoizedSerializedSize() {
    return memoizedSerializedSize;
  }

  public void setMemoizedSerializedSize(Integer memoizedSerializedSize) {
    this.memoizedSerializedSize = memoizedSerializedSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RerunInfo rerunInfo = (RerunInfo) o;
    return Objects.equals(this.unknownFields, rerunInfo.unknownFields) &&
        Objects.equals(this.initialized, rerunInfo.initialized) &&
        Objects.equals(this.rootExecutionId, rerunInfo.rootExecutionId) &&
        Objects.equals(this.rootTriggerTypeValue, rerunInfo.rootTriggerTypeValue) &&
        Objects.equals(this.prevExecutionId, rerunInfo.prevExecutionId) &&
        Objects.equals(this.prevExecutionIdBytes, rerunInfo.prevExecutionIdBytes) &&
        Objects.equals(this.prevTriggerTypeValue, rerunInfo.prevTriggerTypeValue) &&
        Objects.equals(this.prevTriggerType, rerunInfo.prevTriggerType) &&
        Objects.equals(this.rootExecutionIdBytes, rerunInfo.rootExecutionIdBytes) &&
        Objects.equals(this.serializedSize, rerunInfo.serializedSize) &&
        Objects.equals(this.parserForType, rerunInfo.parserForType) &&
        Objects.equals(this.defaultInstanceForType, rerunInfo.defaultInstanceForType) &&
        Objects.equals(this.rootTriggerType, rerunInfo.rootTriggerType) &&
        Objects.equals(this.allFields, rerunInfo.allFields) &&
        Objects.equals(this.initializationErrorString, rerunInfo.initializationErrorString) &&
        Objects.equals(this.descriptorForType, rerunInfo.descriptorForType) &&
        Objects.equals(this.memoizedSerializedSize, rerunInfo.memoizedSerializedSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unknownFields, initialized, rootExecutionId, rootTriggerTypeValue, prevExecutionId, prevExecutionIdBytes, prevTriggerTypeValue, prevTriggerType, rootExecutionIdBytes, serializedSize, parserForType, defaultInstanceForType, rootTriggerType, allFields, initializationErrorString, descriptorForType, memoizedSerializedSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RerunInfo {\n");
    
    sb.append("    unknownFields: ").append(toIndentedString(unknownFields)).append("\n");
    sb.append("    initialized: ").append(toIndentedString(initialized)).append("\n");
    sb.append("    rootExecutionId: ").append(toIndentedString(rootExecutionId)).append("\n");
    sb.append("    rootTriggerTypeValue: ").append(toIndentedString(rootTriggerTypeValue)).append("\n");
    sb.append("    prevExecutionId: ").append(toIndentedString(prevExecutionId)).append("\n");
    sb.append("    prevExecutionIdBytes: ").append(toIndentedString(prevExecutionIdBytes)).append("\n");
    sb.append("    prevTriggerTypeValue: ").append(toIndentedString(prevTriggerTypeValue)).append("\n");
    sb.append("    prevTriggerType: ").append(toIndentedString(prevTriggerType)).append("\n");
    sb.append("    rootExecutionIdBytes: ").append(toIndentedString(rootExecutionIdBytes)).append("\n");
    sb.append("    serializedSize: ").append(toIndentedString(serializedSize)).append("\n");
    sb.append("    parserForType: ").append(toIndentedString(parserForType)).append("\n");
    sb.append("    defaultInstanceForType: ").append(toIndentedString(defaultInstanceForType)).append("\n");
    sb.append("    rootTriggerType: ").append(toIndentedString(rootTriggerType)).append("\n");
    sb.append("    allFields: ").append(toIndentedString(allFields)).append("\n");
    sb.append("    initializationErrorString: ").append(toIndentedString(initializationErrorString)).append("\n");
    sb.append("    descriptorForType: ").append(toIndentedString(descriptorForType)).append("\n");
    sb.append("    memoizedSerializedSize: ").append(toIndentedString(memoizedSerializedSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
