/*
 * CD NextGen API Reference
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 3.0
 * Contact: contact@harness.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResourceGroup;
import io.swagger.client.model.RoleAssignment;
import io.swagger.client.model.RoleResponse;
import io.swagger.client.model.Scope;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * RoleAssignmentAggregateResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T23:54:49.094+05:30[Asia/Kolkata]")
public class RoleAssignmentAggregateResponse {
  @SerializedName("roleAssignments")
  private List<RoleAssignment> roleAssignments = null;

  @SerializedName("scope")
  private Scope scope = null;

  @SerializedName("roles")
  private List<RoleResponse> roles = null;

  @SerializedName("resourceGroups")
  private List<ResourceGroup> resourceGroups = null;

  public RoleAssignmentAggregateResponse roleAssignments(List<RoleAssignment> roleAssignments) {
    this.roleAssignments = roleAssignments;
    return this;
  }

  public RoleAssignmentAggregateResponse addRoleAssignmentsItem(RoleAssignment roleAssignmentsItem) {
    if (this.roleAssignments == null) {
      this.roleAssignments = new ArrayList<RoleAssignment>();
    }
    this.roleAssignments.add(roleAssignmentsItem);
    return this;
  }

   /**
   * Get roleAssignments
   * @return roleAssignments
  **/
  @Schema(description = "")
  public List<RoleAssignment> getRoleAssignments() {
    return roleAssignments;
  }

  public void setRoleAssignments(List<RoleAssignment> roleAssignments) {
    this.roleAssignments = roleAssignments;
  }

  public RoleAssignmentAggregateResponse scope(Scope scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @Schema(description = "")
  public Scope getScope() {
    return scope;
  }

  public void setScope(Scope scope) {
    this.scope = scope;
  }

  public RoleAssignmentAggregateResponse roles(List<RoleResponse> roles) {
    this.roles = roles;
    return this;
  }

  public RoleAssignmentAggregateResponse addRolesItem(RoleResponse rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<RoleResponse>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @Schema(description = "")
  public List<RoleResponse> getRoles() {
    return roles;
  }

  public void setRoles(List<RoleResponse> roles) {
    this.roles = roles;
  }

  public RoleAssignmentAggregateResponse resourceGroups(List<ResourceGroup> resourceGroups) {
    this.resourceGroups = resourceGroups;
    return this;
  }

  public RoleAssignmentAggregateResponse addResourceGroupsItem(ResourceGroup resourceGroupsItem) {
    if (this.resourceGroups == null) {
      this.resourceGroups = new ArrayList<ResourceGroup>();
    }
    this.resourceGroups.add(resourceGroupsItem);
    return this;
  }

   /**
   * Get resourceGroups
   * @return resourceGroups
  **/
  @Schema(description = "")
  public List<ResourceGroup> getResourceGroups() {
    return resourceGroups;
  }

  public void setResourceGroups(List<ResourceGroup> resourceGroups) {
    this.resourceGroups = resourceGroups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoleAssignmentAggregateResponse roleAssignmentAggregateResponse = (RoleAssignmentAggregateResponse) o;
    return Objects.equals(this.roleAssignments, roleAssignmentAggregateResponse.roleAssignments) &&
        Objects.equals(this.scope, roleAssignmentAggregateResponse.scope) &&
        Objects.equals(this.roles, roleAssignmentAggregateResponse.roles) &&
        Objects.equals(this.resourceGroups, roleAssignmentAggregateResponse.resourceGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roleAssignments, scope, roles, resourceGroups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoleAssignmentAggregateResponse {\n");
    
    sb.append("    roleAssignments: ").append(toIndentedString(roleAssignments)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    resourceGroups: ").append(toIndentedString(resourceGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
