/*
 * CD NextGen API Reference
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 3.0
 * Contact: contact@harness.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Descriptor;
import io.swagger.client.model.ParserSyncExecutableResponse;
import io.swagger.client.model.SyncExecutableResponse;
import io.swagger.client.model.UnknownFieldSet;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * SyncExecutableResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T23:54:49.094+05:30[Asia/Kolkata]")
public class SyncExecutableResponse {
  @SerializedName("unknownFields")
  private UnknownFieldSet unknownFields = null;

  @SerializedName("initialized")
  private Boolean initialized = null;

  @SerializedName("serializedSize")
  private Integer serializedSize = null;

  @SerializedName("parserForType")
  private ParserSyncExecutableResponse parserForType = null;

  @SerializedName("defaultInstanceForType")
  private SyncExecutableResponse defaultInstanceForType = null;

  @SerializedName("logKeysList")
  private List<String> logKeysList = null;

  @SerializedName("logKeysCount")
  private Integer logKeysCount = null;

  @SerializedName("unitsList")
  private List<String> unitsList = null;

  @SerializedName("unitsCount")
  private Integer unitsCount = null;

  @SerializedName("allFields")
  private Map<String, Object> allFields = null;

  @SerializedName("initializationErrorString")
  private String initializationErrorString = null;

  @SerializedName("descriptorForType")
  private Descriptor descriptorForType = null;

  @SerializedName("memoizedSerializedSize")
  private Integer memoizedSerializedSize = null;

  public SyncExecutableResponse unknownFields(UnknownFieldSet unknownFields) {
    this.unknownFields = unknownFields;
    return this;
  }

   /**
   * Get unknownFields
   * @return unknownFields
  **/
  @Schema(description = "")
  public UnknownFieldSet getUnknownFields() {
    return unknownFields;
  }

  public void setUnknownFields(UnknownFieldSet unknownFields) {
    this.unknownFields = unknownFields;
  }

  public SyncExecutableResponse initialized(Boolean initialized) {
    this.initialized = initialized;
    return this;
  }

   /**
   * Get initialized
   * @return initialized
  **/
  @Schema(description = "")
  public Boolean isInitialized() {
    return initialized;
  }

  public void setInitialized(Boolean initialized) {
    this.initialized = initialized;
  }

  public SyncExecutableResponse serializedSize(Integer serializedSize) {
    this.serializedSize = serializedSize;
    return this;
  }

   /**
   * Get serializedSize
   * @return serializedSize
  **/
  @Schema(description = "")
  public Integer getSerializedSize() {
    return serializedSize;
  }

  public void setSerializedSize(Integer serializedSize) {
    this.serializedSize = serializedSize;
  }

  public SyncExecutableResponse parserForType(ParserSyncExecutableResponse parserForType) {
    this.parserForType = parserForType;
    return this;
  }

   /**
   * Get parserForType
   * @return parserForType
  **/
  @Schema(description = "")
  public ParserSyncExecutableResponse getParserForType() {
    return parserForType;
  }

  public void setParserForType(ParserSyncExecutableResponse parserForType) {
    this.parserForType = parserForType;
  }

  public SyncExecutableResponse defaultInstanceForType(SyncExecutableResponse defaultInstanceForType) {
    this.defaultInstanceForType = defaultInstanceForType;
    return this;
  }

   /**
   * Get defaultInstanceForType
   * @return defaultInstanceForType
  **/
  @Schema(description = "")
  public SyncExecutableResponse getDefaultInstanceForType() {
    return defaultInstanceForType;
  }

  public void setDefaultInstanceForType(SyncExecutableResponse defaultInstanceForType) {
    this.defaultInstanceForType = defaultInstanceForType;
  }

  public SyncExecutableResponse logKeysList(List<String> logKeysList) {
    this.logKeysList = logKeysList;
    return this;
  }

  public SyncExecutableResponse addLogKeysListItem(String logKeysListItem) {
    if (this.logKeysList == null) {
      this.logKeysList = new ArrayList<String>();
    }
    this.logKeysList.add(logKeysListItem);
    return this;
  }

   /**
   * Get logKeysList
   * @return logKeysList
  **/
  @Schema(description = "")
  public List<String> getLogKeysList() {
    return logKeysList;
  }

  public void setLogKeysList(List<String> logKeysList) {
    this.logKeysList = logKeysList;
  }

  public SyncExecutableResponse logKeysCount(Integer logKeysCount) {
    this.logKeysCount = logKeysCount;
    return this;
  }

   /**
   * Get logKeysCount
   * @return logKeysCount
  **/
  @Schema(description = "")
  public Integer getLogKeysCount() {
    return logKeysCount;
  }

  public void setLogKeysCount(Integer logKeysCount) {
    this.logKeysCount = logKeysCount;
  }

  public SyncExecutableResponse unitsList(List<String> unitsList) {
    this.unitsList = unitsList;
    return this;
  }

  public SyncExecutableResponse addUnitsListItem(String unitsListItem) {
    if (this.unitsList == null) {
      this.unitsList = new ArrayList<String>();
    }
    this.unitsList.add(unitsListItem);
    return this;
  }

   /**
   * Get unitsList
   * @return unitsList
  **/
  @Schema(description = "")
  public List<String> getUnitsList() {
    return unitsList;
  }

  public void setUnitsList(List<String> unitsList) {
    this.unitsList = unitsList;
  }

  public SyncExecutableResponse unitsCount(Integer unitsCount) {
    this.unitsCount = unitsCount;
    return this;
  }

   /**
   * Get unitsCount
   * @return unitsCount
  **/
  @Schema(description = "")
  public Integer getUnitsCount() {
    return unitsCount;
  }

  public void setUnitsCount(Integer unitsCount) {
    this.unitsCount = unitsCount;
  }

  public SyncExecutableResponse allFields(Map<String, Object> allFields) {
    this.allFields = allFields;
    return this;
  }

  public SyncExecutableResponse putAllFieldsItem(String key, Object allFieldsItem) {
    if (this.allFields == null) {
      this.allFields = new HashMap<String, Object>();
    }
    this.allFields.put(key, allFieldsItem);
    return this;
  }

   /**
   * Get allFields
   * @return allFields
  **/
  @Schema(description = "")
  public Map<String, Object> getAllFields() {
    return allFields;
  }

  public void setAllFields(Map<String, Object> allFields) {
    this.allFields = allFields;
  }

  public SyncExecutableResponse initializationErrorString(String initializationErrorString) {
    this.initializationErrorString = initializationErrorString;
    return this;
  }

   /**
   * Get initializationErrorString
   * @return initializationErrorString
  **/
  @Schema(description = "")
  public String getInitializationErrorString() {
    return initializationErrorString;
  }

  public void setInitializationErrorString(String initializationErrorString) {
    this.initializationErrorString = initializationErrorString;
  }

  public SyncExecutableResponse descriptorForType(Descriptor descriptorForType) {
    this.descriptorForType = descriptorForType;
    return this;
  }

   /**
   * Get descriptorForType
   * @return descriptorForType
  **/
  @Schema(description = "")
  public Descriptor getDescriptorForType() {
    return descriptorForType;
  }

  public void setDescriptorForType(Descriptor descriptorForType) {
    this.descriptorForType = descriptorForType;
  }

  public SyncExecutableResponse memoizedSerializedSize(Integer memoizedSerializedSize) {
    this.memoizedSerializedSize = memoizedSerializedSize;
    return this;
  }

   /**
   * Get memoizedSerializedSize
   * @return memoizedSerializedSize
  **/
  @Schema(description = "")
  public Integer getMemoizedSerializedSize() {
    return memoizedSerializedSize;
  }

  public void setMemoizedSerializedSize(Integer memoizedSerializedSize) {
    this.memoizedSerializedSize = memoizedSerializedSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyncExecutableResponse syncExecutableResponse = (SyncExecutableResponse) o;
    return Objects.equals(this.unknownFields, syncExecutableResponse.unknownFields) &&
        Objects.equals(this.initialized, syncExecutableResponse.initialized) &&
        Objects.equals(this.serializedSize, syncExecutableResponse.serializedSize) &&
        Objects.equals(this.parserForType, syncExecutableResponse.parserForType) &&
        Objects.equals(this.defaultInstanceForType, syncExecutableResponse.defaultInstanceForType) &&
        Objects.equals(this.logKeysList, syncExecutableResponse.logKeysList) &&
        Objects.equals(this.logKeysCount, syncExecutableResponse.logKeysCount) &&
        Objects.equals(this.unitsList, syncExecutableResponse.unitsList) &&
        Objects.equals(this.unitsCount, syncExecutableResponse.unitsCount) &&
        Objects.equals(this.allFields, syncExecutableResponse.allFields) &&
        Objects.equals(this.initializationErrorString, syncExecutableResponse.initializationErrorString) &&
        Objects.equals(this.descriptorForType, syncExecutableResponse.descriptorForType) &&
        Objects.equals(this.memoizedSerializedSize, syncExecutableResponse.memoizedSerializedSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unknownFields, initialized, serializedSize, parserForType, defaultInstanceForType, logKeysList, logKeysCount, unitsList, unitsCount, allFields, initializationErrorString, descriptorForType, memoizedSerializedSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyncExecutableResponse {\n");
    
    sb.append("    unknownFields: ").append(toIndentedString(unknownFields)).append("\n");
    sb.append("    initialized: ").append(toIndentedString(initialized)).append("\n");
    sb.append("    serializedSize: ").append(toIndentedString(serializedSize)).append("\n");
    sb.append("    parserForType: ").append(toIndentedString(parserForType)).append("\n");
    sb.append("    defaultInstanceForType: ").append(toIndentedString(defaultInstanceForType)).append("\n");
    sb.append("    logKeysList: ").append(toIndentedString(logKeysList)).append("\n");
    sb.append("    logKeysCount: ").append(toIndentedString(logKeysCount)).append("\n");
    sb.append("    unitsList: ").append(toIndentedString(unitsList)).append("\n");
    sb.append("    unitsCount: ").append(toIndentedString(unitsCount)).append("\n");
    sb.append("    allFields: ").append(toIndentedString(allFields)).append("\n");
    sb.append("    initializationErrorString: ").append(toIndentedString(initializationErrorString)).append("\n");
    sb.append("    descriptorForType: ").append(toIndentedString(descriptorForType)).append("\n");
    sb.append("    memoizedSerializedSize: ").append(toIndentedString(memoizedSerializedSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
