/*
 * CD NextGen API Reference
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 3.0
 * Contact: contact@harness.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.JsonNode;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TemplateLinkConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T23:54:49.094+05:30[Asia/Kolkata]")
public class TemplateLinkConfig {
  @SerializedName("templateRef")
  private String templateRef = null;

  @SerializedName("versionLabel")
  private String versionLabel = null;

  @SerializedName("templateInputs")
  private JsonNode templateInputs = null;

  @SerializedName("__uuid")
  private String _uuid = null;

  public TemplateLinkConfig templateRef(String templateRef) {
    this.templateRef = templateRef;
    return this;
  }

   /**
   * Get templateRef
   * @return templateRef
  **/
  @Schema(required = true, description = "")
  public String getTemplateRef() {
    return templateRef;
  }

  public void setTemplateRef(String templateRef) {
    this.templateRef = templateRef;
  }

  public TemplateLinkConfig versionLabel(String versionLabel) {
    this.versionLabel = versionLabel;
    return this;
  }

   /**
   * Get versionLabel
   * @return versionLabel
  **/
  @Schema(description = "")
  public String getVersionLabel() {
    return versionLabel;
  }

  public void setVersionLabel(String versionLabel) {
    this.versionLabel = versionLabel;
  }

  public TemplateLinkConfig templateInputs(JsonNode templateInputs) {
    this.templateInputs = templateInputs;
    return this;
  }

   /**
   * Get templateInputs
   * @return templateInputs
  **/
  @Schema(description = "")
  public JsonNode getTemplateInputs() {
    return templateInputs;
  }

  public void setTemplateInputs(JsonNode templateInputs) {
    this.templateInputs = templateInputs;
  }

  public TemplateLinkConfig _uuid(String _uuid) {
    this._uuid = _uuid;
    return this;
  }

   /**
   * Get _uuid
   * @return _uuid
  **/
  @Schema(description = "")
  public String getUuid() {
    return _uuid;
  }

  public void setUuid(String _uuid) {
    this._uuid = _uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateLinkConfig templateLinkConfig = (TemplateLinkConfig) o;
    return Objects.equals(this.templateRef, templateLinkConfig.templateRef) &&
        Objects.equals(this.versionLabel, templateLinkConfig.versionLabel) &&
        Objects.equals(this.templateInputs, templateLinkConfig.templateInputs) &&
        Objects.equals(this._uuid, templateLinkConfig._uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateRef, versionLabel, templateInputs, _uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateLinkConfig {\n");
    
    sb.append("    templateRef: ").append(toIndentedString(templateRef)).append("\n");
    sb.append("    versionLabel: ").append(toIndentedString(versionLabel)).append("\n");
    sb.append("    templateInputs: ").append(toIndentedString(templateInputs)).append("\n");
    sb.append("    _uuid: ").append(toIndentedString(_uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
