/*
 * CD NextGen API Reference
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 3.0
 * Contact: contact@harness.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ByteString;
import io.swagger.client.model.Descriptor;
import io.swagger.client.model.ParserYamlOutputProperties;
import io.swagger.client.model.UnknownFieldSet;
import io.swagger.client.model.YamlOutputProperties;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * YamlOutputProperties
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T23:54:49.094+05:30[Asia/Kolkata]")
public class YamlOutputProperties {
  @SerializedName("unknownFields")
  private UnknownFieldSet unknownFields = null;

  @SerializedName("localName")
  private String localName = null;

  @SerializedName("initialized")
  private Boolean initialized = null;

  @SerializedName("fqn")
  private String fqn = null;

  @SerializedName("serializedSize")
  private Integer serializedSize = null;

  @SerializedName("parserForType")
  private ParserYamlOutputProperties parserForType = null;

  @SerializedName("defaultInstanceForType")
  private YamlOutputProperties defaultInstanceForType = null;

  @SerializedName("fqnBytes")
  private ByteString fqnBytes = null;

  @SerializedName("localNameBytes")
  private ByteString localNameBytes = null;

  @SerializedName("allFields")
  private Map<String, Object> allFields = null;

  @SerializedName("initializationErrorString")
  private String initializationErrorString = null;

  @SerializedName("descriptorForType")
  private Descriptor descriptorForType = null;

  @SerializedName("memoizedSerializedSize")
  private Integer memoizedSerializedSize = null;

  public YamlOutputProperties unknownFields(UnknownFieldSet unknownFields) {
    this.unknownFields = unknownFields;
    return this;
  }

   /**
   * Get unknownFields
   * @return unknownFields
  **/
  @Schema(description = "")
  public UnknownFieldSet getUnknownFields() {
    return unknownFields;
  }

  public void setUnknownFields(UnknownFieldSet unknownFields) {
    this.unknownFields = unknownFields;
  }

  public YamlOutputProperties localName(String localName) {
    this.localName = localName;
    return this;
  }

   /**
   * Get localName
   * @return localName
  **/
  @Schema(description = "")
  public String getLocalName() {
    return localName;
  }

  public void setLocalName(String localName) {
    this.localName = localName;
  }

  public YamlOutputProperties initialized(Boolean initialized) {
    this.initialized = initialized;
    return this;
  }

   /**
   * Get initialized
   * @return initialized
  **/
  @Schema(description = "")
  public Boolean isInitialized() {
    return initialized;
  }

  public void setInitialized(Boolean initialized) {
    this.initialized = initialized;
  }

  public YamlOutputProperties fqn(String fqn) {
    this.fqn = fqn;
    return this;
  }

   /**
   * Get fqn
   * @return fqn
  **/
  @Schema(description = "")
  public String getFqn() {
    return fqn;
  }

  public void setFqn(String fqn) {
    this.fqn = fqn;
  }

  public YamlOutputProperties serializedSize(Integer serializedSize) {
    this.serializedSize = serializedSize;
    return this;
  }

   /**
   * Get serializedSize
   * @return serializedSize
  **/
  @Schema(description = "")
  public Integer getSerializedSize() {
    return serializedSize;
  }

  public void setSerializedSize(Integer serializedSize) {
    this.serializedSize = serializedSize;
  }

  public YamlOutputProperties parserForType(ParserYamlOutputProperties parserForType) {
    this.parserForType = parserForType;
    return this;
  }

   /**
   * Get parserForType
   * @return parserForType
  **/
  @Schema(description = "")
  public ParserYamlOutputProperties getParserForType() {
    return parserForType;
  }

  public void setParserForType(ParserYamlOutputProperties parserForType) {
    this.parserForType = parserForType;
  }

  public YamlOutputProperties defaultInstanceForType(YamlOutputProperties defaultInstanceForType) {
    this.defaultInstanceForType = defaultInstanceForType;
    return this;
  }

   /**
   * Get defaultInstanceForType
   * @return defaultInstanceForType
  **/
  @Schema(description = "")
  public YamlOutputProperties getDefaultInstanceForType() {
    return defaultInstanceForType;
  }

  public void setDefaultInstanceForType(YamlOutputProperties defaultInstanceForType) {
    this.defaultInstanceForType = defaultInstanceForType;
  }

  public YamlOutputProperties fqnBytes(ByteString fqnBytes) {
    this.fqnBytes = fqnBytes;
    return this;
  }

   /**
   * Get fqnBytes
   * @return fqnBytes
  **/
  @Schema(description = "")
  public ByteString getFqnBytes() {
    return fqnBytes;
  }

  public void setFqnBytes(ByteString fqnBytes) {
    this.fqnBytes = fqnBytes;
  }

  public YamlOutputProperties localNameBytes(ByteString localNameBytes) {
    this.localNameBytes = localNameBytes;
    return this;
  }

   /**
   * Get localNameBytes
   * @return localNameBytes
  **/
  @Schema(description = "")
  public ByteString getLocalNameBytes() {
    return localNameBytes;
  }

  public void setLocalNameBytes(ByteString localNameBytes) {
    this.localNameBytes = localNameBytes;
  }

  public YamlOutputProperties allFields(Map<String, Object> allFields) {
    this.allFields = allFields;
    return this;
  }

  public YamlOutputProperties putAllFieldsItem(String key, Object allFieldsItem) {
    if (this.allFields == null) {
      this.allFields = new HashMap<String, Object>();
    }
    this.allFields.put(key, allFieldsItem);
    return this;
  }

   /**
   * Get allFields
   * @return allFields
  **/
  @Schema(description = "")
  public Map<String, Object> getAllFields() {
    return allFields;
  }

  public void setAllFields(Map<String, Object> allFields) {
    this.allFields = allFields;
  }

  public YamlOutputProperties initializationErrorString(String initializationErrorString) {
    this.initializationErrorString = initializationErrorString;
    return this;
  }

   /**
   * Get initializationErrorString
   * @return initializationErrorString
  **/
  @Schema(description = "")
  public String getInitializationErrorString() {
    return initializationErrorString;
  }

  public void setInitializationErrorString(String initializationErrorString) {
    this.initializationErrorString = initializationErrorString;
  }

  public YamlOutputProperties descriptorForType(Descriptor descriptorForType) {
    this.descriptorForType = descriptorForType;
    return this;
  }

   /**
   * Get descriptorForType
   * @return descriptorForType
  **/
  @Schema(description = "")
  public Descriptor getDescriptorForType() {
    return descriptorForType;
  }

  public void setDescriptorForType(Descriptor descriptorForType) {
    this.descriptorForType = descriptorForType;
  }

  public YamlOutputProperties memoizedSerializedSize(Integer memoizedSerializedSize) {
    this.memoizedSerializedSize = memoizedSerializedSize;
    return this;
  }

   /**
   * Get memoizedSerializedSize
   * @return memoizedSerializedSize
  **/
  @Schema(description = "")
  public Integer getMemoizedSerializedSize() {
    return memoizedSerializedSize;
  }

  public void setMemoizedSerializedSize(Integer memoizedSerializedSize) {
    this.memoizedSerializedSize = memoizedSerializedSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    YamlOutputProperties yamlOutputProperties = (YamlOutputProperties) o;
    return Objects.equals(this.unknownFields, yamlOutputProperties.unknownFields) &&
        Objects.equals(this.localName, yamlOutputProperties.localName) &&
        Objects.equals(this.initialized, yamlOutputProperties.initialized) &&
        Objects.equals(this.fqn, yamlOutputProperties.fqn) &&
        Objects.equals(this.serializedSize, yamlOutputProperties.serializedSize) &&
        Objects.equals(this.parserForType, yamlOutputProperties.parserForType) &&
        Objects.equals(this.defaultInstanceForType, yamlOutputProperties.defaultInstanceForType) &&
        Objects.equals(this.fqnBytes, yamlOutputProperties.fqnBytes) &&
        Objects.equals(this.localNameBytes, yamlOutputProperties.localNameBytes) &&
        Objects.equals(this.allFields, yamlOutputProperties.allFields) &&
        Objects.equals(this.initializationErrorString, yamlOutputProperties.initializationErrorString) &&
        Objects.equals(this.descriptorForType, yamlOutputProperties.descriptorForType) &&
        Objects.equals(this.memoizedSerializedSize, yamlOutputProperties.memoizedSerializedSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unknownFields, localName, initialized, fqn, serializedSize, parserForType, defaultInstanceForType, fqnBytes, localNameBytes, allFields, initializationErrorString, descriptorForType, memoizedSerializedSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class YamlOutputProperties {\n");
    
    sb.append("    unknownFields: ").append(toIndentedString(unknownFields)).append("\n");
    sb.append("    localName: ").append(toIndentedString(localName)).append("\n");
    sb.append("    initialized: ").append(toIndentedString(initialized)).append("\n");
    sb.append("    fqn: ").append(toIndentedString(fqn)).append("\n");
    sb.append("    serializedSize: ").append(toIndentedString(serializedSize)).append("\n");
    sb.append("    parserForType: ").append(toIndentedString(parserForType)).append("\n");
    sb.append("    defaultInstanceForType: ").append(toIndentedString(defaultInstanceForType)).append("\n");
    sb.append("    fqnBytes: ").append(toIndentedString(fqnBytes)).append("\n");
    sb.append("    localNameBytes: ").append(toIndentedString(localNameBytes)).append("\n");
    sb.append("    allFields: ").append(toIndentedString(allFields)).append("\n");
    sb.append("    initializationErrorString: ").append(toIndentedString(initializationErrorString)).append("\n");
    sb.append("    descriptorForType: ").append(toIndentedString(descriptorForType)).append("\n");
    sb.append("    memoizedSerializedSize: ").append(toIndentedString(memoizedSerializedSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
